name: cima_client
description: CIMA client to access Medication data source
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  cima_api:
    path: packages/cima_api
  cima_model:
    path: packages/cima_model
  cima_repository:
    path: packages/cima_repository
  collection: ^1.16.0
  equatable: ^2.0.3
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  formz_inputs:
    path: packages/formz_inputs
  go_router: ^6.5.3
  intl: ^0.17.0
  package_info_plus: ^3.0.2
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
