name: cima_client
description: CIMA client to acces Meication data source
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cima_api:
    path: packages/cima_api
  cima_repository:
    path: packages/cima_repository
  cima_model:
    path: packages/cima_model
  formz_inputs:
    path: packages/formz_inputs
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_localizations:
    sdk: flutter
  intl: any
  url_launcher: any
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
