name: cima_client
description: CIMA client to acces Meication data source
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cima_api:
    path: packages/cima_api
  cima_repository:
    path: packages/cima_repository
  cima_model:
    path: packages/cima_model
  equatable: ^2.0.3
  formz_inputs:
    path: packages/formz_inputs
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.1.7
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
