name: cima_api
description: CIMA API Client
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.22.1
  mocktail: ^0.3.0
  lints: ^2.0.1
