name: cima_model
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  equatable: any
  json_annotation: any

dev_dependencies:
  build_runner: any
  json_serializable: any
  lints: any
  test: ^1.17.0
