name: utils
description: A set of utility commands.
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
