name: cima_client

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analize
        run: flutter analyze

      - name: Run Test
        run: flutter test --no-pub --coverage

      - name: Check Code Coverage
        uses: VeryGoodOpensource/very_good_coverage@v1.1.1